services:
  quizz-db:
    image: mongo
    container_name: quizz-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: quizz
    ports:
      - "27017:27017"
    volumes:
      - quizz-data:/data/db
      - ./../scripts/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js

  quizz-service:
    container_name: quizz-service
    build:
      context: ../
      dockerfile: ./docker/quizz-service-dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - quizz-db

volumes:
  quizz-data:
