name: CI/CD Quizz Backend Microservice

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Go into backend folder
        run: cd backend/

      - name: Set up .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Restore dependencies
        run: dotnet restore backend/QuizzService.sln

      - name: Build
        run: dotnet build backend/QuizzService.sln --configuration Release

      - name: Test
        run: dotnet test backend/QuizzService.sln --configuration Release --no-build
